name = "MC1.19.2"
author = "TN_TechNoob"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d28614eab13fd0ddd3c4e42da09d44383833509121fa11eaf83e336dc33daa"

[versions]
fabric = "0.16.9"
minecraft = "1.19.2"
